export const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    CHANGE_INFO : 'CHANGE_INFO',
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
    GET_CATEGORY: 'GET_CATEGORY',
    GET_PRICE: 'GET_PRICE',
    GET_ACREAGE: 'GET_ACREAGE'
}


